name: Main
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec bundle audit --update
        bundle exec rubocop --parallel
        bundle exec rake test
