name: Main
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get install libsqlite3-dev
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - run: bundle config path vendor/bundle
    - run: bundle install --jobs 4 --retry 3
    - run: bundle exec bundle audit --update
    - run: bundle exec rubocop --parallel
    - run: bundle exec rake test
      env:
        CI: true
